# Generated by Django 5.0.4 on 2024-05-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='status',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_name',
            new_name='task',
        ),
    ]
